#!/bin/bash

cam="/dev/video0"

#mjpg_streamer \
#	-i '/usr/local/lib/mjpg-streamer/input_uvc.so \
#	-d ${cam} \
#	-r 1024x576 \
#	-f 5 \
#	-q 75' \
#	-o '/usr/local/lib/mjpg-streamer/output_http.so \
#	-p 8080'

mjpg_streamer \
	-i "/usr/local/lib/mjpg-streamer/input_uvc.so -n -f 10 -r 1280x720" \
	-o "/usr/local/lib/mjpg-streamer/output_http.so -p 8080"


# > v4l2-ctl --list-devices
# HD Pro Webcam C920 (usb-3f980000.usb-1.3):
# 	/dev/video0
# 	/dev/video1

